### ISSUE TITLE
[Request]: Pop-up info on mouse hover

### ISSUE THREAD

**Issue by aeq-dev** [GuavaCZ/calendar#14]
### What feature would you like to add?

If we can show a pop-up for more details on event mouse hover or on an icon click :)
Thanks

**Comment by lukas-frey** [comment]
Hi, since mouse hover works only on desktop and is not very mobile friendly, this is not something that I plan on adding currently.

However, since you can define your own eventContent, you can simply use alpineJS to render anything you want on hover. You can use [alpinejs-tooltip](https://github.com/ryangjchandler/alpine-tooltip) for example to add a tooltip on hover.

**Comment by aeq-dev** [comment]
Yes ! thanks for suggestion :)))))

**Comment by Altffenser** [comment]
I implemented it just as @lukas-frey indicates, it is possible and 100% customizable.
![imagen](https://github.com/user-attachments/assets/a66c96c8-a4d4-4b0f-aff3-ffb3c104f4ed)
(Spanish UI)

**Comment by lukas-frey** [comment]
That looks very nice! Good job 🙂

**Comment by aeq-dev** [comment]
@Altffenser WOOW! So nice! could you please share with us its code if you don't mind ? thanks :))))
